# -*- coding: utf-8 -*-
"""sentiment analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eCJ7Ys5oXVZbNQhkeN88MWiVO5WlAzjc
"""

# !pip -q install requests beautifulsoup4 pandas spacy transformers tqdm datasets pandas_market_calendars
# !python -m spacy download en_core_web_sm -q

import torch
import os, re, time, datetime as dt, collections, requests, json, textwrap
from pathlib import Path
import pandas as pd
from bs4 import BeautifulSoup
import spacy
from transformers import pipeline
from tqdm.notebook import tqdm  # Colab‑friendly progress bar

# -------- parameters --------
TICKERS  = ["AMZN","AXP","AMGN","AAPL","BA","CAT","CSCO","CVX","GS","HD",
            "HON","IBM","JNJ","MCD","MMM","MRK","MSFT","NKE","PG","SHW",
            "TRV","UNH","CRM","NVDA","VZ","V","WMT","DIS"]
START    = "2024-04-01"        # inclusive lower bound
END      = "2025-04-16"        # inclusive upper bound
MAX_NEWS = 100                 # google max per query
OUT_DIR  = Path("/content")
UA_HDR   = {"User-Agent": ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                           "AppleWebKit/537.36 (KHTML, like Gecko) "
                           "Chrome/122.0.0.0 Safari/537.36")}
# --------------------------------------------

# 3) load models
import torch


device = 0 if torch.cuda.is_available() else -1
print(f"[INFO] running sentiment pipeline on device {device}")

sentiment = pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english",
    device=device
)

def google_html(query:str, n:int=100)->list[dict]:
    url = ("https://www.google.com/search"
           f"?q={requests.utils.quote(query)}&gl=us&tbm=nws&num={n}")
    html = requests.get(url, headers=UA_HDR, timeout=10).text
    soup = BeautifulSoup(html, "html.parser")
    hits=[]
    for el in soup.select("div.SoaBEf"):
        hits.append(dict(
            link    = el.find("a")["href"],
            title   = el.select_one("div.MBeuO").get_text(strip=True),
            snippet = el.select_one(".GI74Re").get_text(" ", strip=True),
            date_lab= el.select_one(".LfVVr").get_text(strip=True),
            source  = el.select_one(".NUnG9d span").get_text(strip=True)
        ))
    return hits

def label_to_date(label:str)->dt.date|None:
    label=label.lower(); today=dt.date.today()
    if "hour" in label or "min" in label: return today
    if "day"  in label:
        n=int(re.search(r"\d+", label)[0]); return today-dt.timedelta(days=n)
    try: return dt.datetime.strptime(label[:12], "%b %d, %Y").date()
    except: return None

def scrape_article(url:str)->str:
    try:
        html=requests.get(url, headers=UA_HDR, timeout=10).text
        soup=BeautifulSoup(html,"html.parser")
        return " ".join(p.get_text(' ',strip=True) for p in soup.find_all("p"))
    except: return ""

def clean(txt:str)->str:
    doc=nlp(txt)
    return " ".join(t.lemma_ for t in doc if not t.is_stop and not t.is_punct)

def starscore(txt:str)->float:
    tot=n=0
    for ck in (txt[i:i+500] for i in range(0,len(txt),500)):
        best=max(unwrap(star(ck)), key=lambda d:d["score"])
        tot+=STAR_MAP[best["label"]]; n+=1
    return tot/n if n else 3.0

def bestemo(txt:str)->str:
    cnt=collections.Counter()
    for ck in (txt[i:i+500] for i in range(0,len(txt),500)):
        best=max(unwrap(emo(ck)), key=lambda d:d["score"])
        cnt[best["label"]]+=1
    return cnt.most_common(1)[0][0] if cnt else "neutral"

from datasets import Dataset
import xml.etree.ElementTree as ET
import datetime as dt
from tqdm.notebook import tqdm
import pandas as pd
import pandas_market_calendars as mcal
import time

# 0) build list of trading dates (excludes weekends & NYSE holidays)
nyse = mcal.get_calendar('NYSE')
schedule = nyse.schedule(start_date=START, end_date=END)
trading_days = schedule.index.normalize().date  # numpy array of datetime.date

# helper to fetch exactly one day's RSS headlines
def fetch_rss_for_date(ticker: str, date: dt.date):
    after  = date.isoformat()
    before = (date + dt.timedelta(days=1)).isoformat()
    url    = (
      "https://news.google.com/rss/search"
      f"?q={requests.utils.quote(f'{ticker}+after:{after}+before:{before}')}"
      "&hl=en-US&gl=US&ceid=US:en"
    )
    r = requests.get(url, headers=UA_HDR, timeout=10)
    if r.status_code != 200:
        return []
    root = ET.fromstring(r.content)
    return [{"date": after, "text": it.findtext("title","")}
            for it in root.findall(".//item")]

# helper to flatten nested lists
def unwrap(x):
    while isinstance(x, list) and x:
        x = x[0]
    return x

combined = []

for tic in tqdm(TICKERS, desc="Tickers"):
    # 1) gather records on trading days only
    records = []
    for pub in trading_days:
        hits = fetch_rss_for_date(tic, pub)
        if hits:
            records.extend(hits)
        else:
            records.append({"date": pub.isoformat(), "text": ""})
        time.sleep(0.2)

    # 2) build per‑ticker dataset
    ds = Dataset.from_list(records)

    # 3) batch BERT sentiment
    def map_sent(batch):
        preds = sentiment(
            batch["text"],
            batch_size=16,
            truncation=True,
            padding=True,
            max_length=512
        )
        # POSITIVE→score, NEGATIVE→1-score
        scores = []
        for p in preds:
            d = unwrap(p)
            scores.append(d["score"] if d["label"]=="POSITIVE" else 1-d["score"])
        return {"sentiment_score": scores}

    ds = ds.map(map_sent, batched=True, batch_size=16)

    # 4) to pandas & aggregate per date
    df = ds.to_pandas()
    daily = (
      df.groupby("date", as_index=False)
        .agg(sentiment_score=("sentiment_score","mean"))
    )

    # 5) save immediately
    out = OUT_DIR / f"{tic}_daily_sentiment.csv"
    daily.to_csv(out, index=False)
    print(f"[INFO] {tic}: {len(daily)} days → {out.name}")

    daily["ticker"] = tic
    combined.append(daily)

# 6) combined CSV
if combined:
    big = pd.concat(combined, ignore_index=True)
    big.to_csv(OUT_DIR/"all_tickers_daily_sentiment.csv", index=False)
    print("[INFO] wrote combined CSV")