# -*- coding: utf-8 -*-
"""sentiment analysis_binaryclassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eCJ7Ys5oXVZbNQhkeN88MWiVO5WlAzjc
"""

!pip install -q requests pandas pandas_market_calendars datasets transformers \
               spacy beautifulsoup4 tqdm nltk pysentiment2
!python -m spacy download en_core_web_sm -q
import nltk; nltk.download('vader_lexicon')

import torch
import os, re, time, datetime as dt, collections, requests, json, textwrap
from pathlib import Path
import pandas as pd
from bs4 import BeautifulSoup
from transformers import pipeline
from tqdm.notebook import tqdm  # Colab‑friendly progress bar
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer


TICKERS  = ["NVDA","AMZN","AXP","AMGN","AAPL","BA","CAT","CSCO","CVX","GS","HD",
            "HON","IBM","JNJ","MCD","MMM","MRK","MSFT","NKE","PG","SHW",
            "TRV","UNH","CRM","VZ","V","WMT","DIS"]
START    = "2025-01-01"        # inclusive lower bound
END      = "2025-04-16"        # inclusive upper bound
MAX_NEWS = 100                 # google max per query
OUT_DIR  = Path("/content")
UA_HDR   = {"User-Agent": ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                           "AppleWebKit/537.36 (KHTML, like Gecko) "
                           "Chrome/122.0.0.0 Safari/537.36")}

# 3) load models
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

device = 0 if torch.cuda.is_available() else -1
print(f"[INFO] running sentiment pipeline on device {device}")

print("[INFO] loading FinBERT")
FINBERT    = "ProsusAI/finbert"
tokenizer  = AutoTokenizer.from_pretrained(FINBERT)
fb_model   = AutoModelForSequenceClassification.from_pretrained(FINBERT)
finbert    = pipeline(
    "sentiment-analysis",
    model=fb_model,
    tokenizer=tokenizer,
    device=device,
    return_all_scores=True,
    top_k=None
)

def google_html(query:str, n:int=100)->list[dict]:
    url = ("https://www.google.com/search"
           f"?q={requests.utils.quote(query)}&gl=us&tbm=nws&num={n}")
    html = requests.get(url, headers=UA_HDR, timeout=10).text
    soup = BeautifulSoup(html, "html.parser")
    hits=[]
    for el in soup.select("div.SoaBEf"):
        hits.append(dict(
            link    = el.find("a")["href"],
            title   = el.select_one("div.MBeuO").get_text(strip=True),
            snippet = el.select_one(".GI74Re").get_text(" ", strip=True),
            date_lab= el.select_one(".LfVVr").get_text(strip=True),
            source  = el.select_one(".NUnG9d span").get_text(strip=True)
        ))
    return hits

def label_to_date(label:str)->dt.date|None:
    label=label.lower(); today=dt.date.today()
    if "hour" in label or "min" in label: return today
    if "day"  in label:
        n=int(re.search(r"\d+", label)[0]); return today-dt.timedelta(days=n)
    try: return dt.datetime.strptime(label[:12], "%b %d, %Y").date()
    except: return None

def scrape_article(url:str)->str:
    try:
        html=requests.get(url, headers=UA_HDR, timeout=10).text
        soup=BeautifulSoup(html,"html.parser")
        return " ".join(p.get_text(' ',strip=True) for p in soup.find_all("p"))
    except: return ""


def text_cleaning(text: str) -> str:
    """Strip HTML, bracketed notes, and non‑alphanumerics except comma/apostrophe."""
    soup = BeautifulSoup(text, "html.parser")
    txt  = re.sub(r'\[[^]]*\]', '', soup.get_text())
    return re.sub(r"[^a-zA-Z0-9\s,']", "", txt)

from datasets import Dataset
import xml.etree.ElementTree as ET
import datetime as dt
from tqdm.notebook import tqdm
import pandas as pd
import pandas_market_calendars as mcal
import time
import pysentiment2 as ps
import math


print("[INFO] loading VADER")
vader = SentimentIntensityAnalyzer()

print("[INFO] loading Loughran–McDonald")
lm = ps.LM()  # pysentiment2 Loughran–McDonald

# ─── Trading days ───────────────────────────────────────────────────────
nyse         = mcal.get_calendar("NYSE")
schedule     = nyse.schedule(start_date=START, end_date=END)
trading_days = schedule.index.normalize().date  # array of datetime.date

# ─── Voting helper ──────────────────────────────────────────────────────
def vote_label(fb_score, vd_score, lm_score):
    votes = []
    # FB: threshold 0.5
    votes.append("positive" if fb_score>0.5 else "negative")
    # VADER: >0.6 pos, <0.4 neg, else neutral
    if vd_score>0.6: votes.append("positive")
    elif vd_score<0.4: votes.append("negative")
    else: votes.append("neutral")
    # Loughran: >0 pos, <0 neg, else neutral
    if lm_score>0: votes.append("positive")
    elif lm_score<0: votes.append("negative")
    else: votes.append("neutral")
    # majority vote
    return max(set(votes), key=votes.count)

# ─── Main per‑ticker loop ───────────────────────────────────────────────
combined = []
for tic in tqdm(TICKERS, desc="Tickers"):
    # collect all (date, text)
    records = []
    for day in trading_days:
        records.extend(fetch_rss_for_date(tic, day))
        time.sleep(0.1)
    ds = Dataset.from_list(records)

    # map_signals → numeric scores
    def map_signals(batch):
        texts    = [text_cleaning(t) for t in batch["text"]]
        fb_preds = finbert(texts, batch_size=32, truncation=True,
                           padding=True, max_length=512)
        vd_scores= [(vader.polarity_scores(t)["compound"]+1)/2
                     for t in texts]
        lm_scores= []
        for t in texts:
            cts = lm.get_score(lm.tokenize(t))
            pos = cts.get("Positive",0); neg = cts.get("Negative",0)
            lm_scores.append((pos-neg)/(pos+neg+1))

        fb_vals = []
        for p in fb_preds:
            items = p if isinstance(p,list) else [p]
            pos   = next((d["score"] for d in items
                           if d["label"].lower()=="positive"), None)
            neg   = next((d["score"] for d in items
                           if d["label"].lower()=="negative"), None)
            fb_vals.append(((pos-neg+1)/2) if pos and neg else (pos or 0.5))

        return {"fb":fb_vals,"vd":vd_scores,"lm":lm_scores}

    ds = ds.map(map_signals, batched=True, batch_size=32)
    df = ds.to_pandas()

    # aggregate per date into one vote
    daily = []
    for date, group in df.groupby("date"):
        fb_mean = group["fb"].mean()
        vd_mean = group["vd"].mean()
        lm_mean = group["lm"].mean()
        label   = vote_label(fb_mean, vd_mean, lm_mean)
        daily.append({"date": date, "sentiment": label})
    daily = pd.DataFrame(daily)

    # save per‑ticker CSV
    out = OUT_DIR / f"{tic}_daily_sentiment.csv"
    daily.to_csv(out, index=False)
    print(f"[INFO] {tic}: {len(daily)} days → {out.name}")

    daily["ticker"] = tic
    combined.append(daily)

# ─── Combined CSV ────────────────────────────────────────────────────
if combined:
    all_df   = pd.concat(combined, ignore_index=True)
    all_path = OUT_DIR / "all_tickers_daily_sentiment.csv"
    all_df.to_csv(all_path, index=False)
    print(f"[INFO] combined CSV saved → {all_path.name}")
else:
    print("[WARN] no data generated")